# Production environment values
replicaCount: 2
image:
  repository: amokscience/hello
  pullPolicy: IfNotPresent
  tag: "prod-latest"

env:
  HTTP_PORT: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

ingress:
  enabled: true
  host: prod.hello.local

serviceAccount:
  create: true
  name: hello

autoscaling:
  enabled: false
