apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

# Patch ConfigMap with prod-specific values
patches:
- path: configmap-patch.yaml

# Patch Secret with prod-specific API key
secretGenerator:
- name: cfb-secrets
  literals:
  - cfbd-api-key=your_prod_api_key_here
  behavior: merge
