# Dev environment values
replicaCount: 1
image:
  repository: amokscience/cfb
  pullPolicy: IfNotPresent
  tag: "dev-3643a90e8e9af7a1fa92084ab0028bf937c155f6"

env:
  HTTP_PORT: 8070
  CFBD_API_BASE: https://api.collegefootballdata.com

secrets:
  cfbdApiKey: 2c18IFOOtCOAhtcWVwkR7f00CgfnhIt7EsLdB4law+9wpZD9BDA9HvPMkfT2S9nG
  redisAddr: redis.local:6379

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 100Mi

ingress:
  enabled: true
  host: dev.cfb.local
