# Production environment values
replicaCount: 2
image:
  repository: amokscience/cfb
  pullPolicy: IfNotPresent
  tag: "prod-latest"

env:
  HTTP_PORT: 8080
  CFBD_API_BASE: https://api.collegefootballdata.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

ingress:
  enabled: true
  host: prod.cfb.local
