{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello-external-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store-hello
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretName }}
    creationPolicy: Owner
  data:
  - secretKey: config
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecrets.secretName }}
{{- end }}
