{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store-hello
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.awsRegion }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: accessKeyID
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secretAccessKey
{{- end }}
