apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config-hello-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/gitops
    targetRevision: HEAD
    path: external-secrets/hello/helm
    helm:
      valueFiles:
        - values-qa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
