namespace: dev

externalSecrets:
  enabled: true
  awsRegion: us-west-2
  awsSecrets:
    cfbdApiKey:
      name: cfb
      key: cfbdApiKey
    redisAddr:
      name: redis-addr
      key: redis-addr
  serviceAccountName: cfb
