{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cfb-external-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cfbd-api-key: '{{ "{{ .cfb | fromJson | index \"cfb\" }}" }}'
        redis-addr: '{{ "{{ .redisaddr | fromJson | index \"redis-addr\" }}" }}'
  dataFrom:
  - extract:
      key: {{ .Values.externalSecrets.awsSecrets.cfbdApiKey }}
      metadataPolicy: None
    rewrite:
      - regexp:
          source: "(.*)"
          target: "cfb"
  - extract:
      key: {{ .Values.externalSecrets.awsSecrets.redisAddr }}
      metadataPolicy: None
    rewrite:
      - regexp:
          source: "(.*)"
          target: "redisaddr"
{{- end }}
