{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cfb-external-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: {{ include "cfb.fullname" . }}-secrets
    creationPolicy: Owner
  data:
  - secretKey: cfbd-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecrets.cfbdApiKey }}
  - secretKey: redis-addr
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecrets.redisAddr }}
{{- end }}
