{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cfb-external-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretName }}
    creationPolicy: Owner
  data:
  - secretKey: cfbd-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecrets.cfbdApiKey }}
    sourceTemplate:
      engine: jinja2
      data: '{{ "{{ .cfb }}" }}'
  - secretKey: redis-addr
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecrets.redisAddr }}
    sourceTemplate:
      engine: jinja2
      data: '{{ "{{ .[\"redis-addr\"] }}" }}'
{{- end }}
