{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cfb-external-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: cfb-secrets
    creationPolicy: Owner
  data:
  - secretKey: cfbd-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecrets.cfbdApiKey.name }}
      property: {{ .Values.externalSecrets.awsSecrets.cfbdApiKey.key }}
  - secretKey: redis-addr
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecrets.redisAddr.name }}
      property: {{ .Values.externalSecrets.awsSecrets.redisAddr.key }}
{{- end }}
