apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cfb

# Reference the Helm chart as the base
helmCharts:
- name: cfb
  repo: ""
  releaseName: cfb
  namespace: cfb
  valuesFile: helm/values.yaml

# Generate secrets from literal values
secretGenerator:
- name: cfb-secrets
  envs:
  - .env.secret
