apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cfb.fullname" . }}-config
  labels:
    {{- include "cfb.labels" . | nindent 4 }}
data:
  HTTP_PORT: "{{ .Values.env.HTTP_PORT }}"
  CFBD_API_BASE: "{{ .Values.env.CFBD_API_BASE }}"
  REDIS_ADDR: "{{ .Values.env.REDIS_ADDR }}"
