apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cfb.fullname" . }}-secrets
  labels:
    {{- include "cfb.labels" . | nindent 4 }}
type: Opaque
data:
  cfbd-api-key: {{ .Values.secrets.cfbdApiKey | b64enc | quote }}
