apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cfb.fullname" . }}-secrets
  labels:
    {{- include "cfb.labels" . | nindent 4 }}
type: Opaque
stringData:
  cfbd-api-key: {{ .Values.secrets.cfbdApiKey | quote }}
  redis-addr: {{ .Values.secrets.redisAddr | quote }}
